-- Useage example:
-- To get the damageMultiplier of the current difficulty: HORDE.Difficulty[HORDE.CurrentDifficulty].damageMultiplier

HORDE.Difficulty = {
    [1] = {
        name = "NORMAL",
		description = "The easiest difficulty. Enemies are slow, but still hit hard.",
        damageMultiplier = 1,
        enemyCountMultiplier = 1,
        rewardMultiplier = 1,
        healthMultiplier = 1,
        startMoneyMultiplier = 1,
        spawnRadiusMultiplier = 1,
        maxEnemiesAliveScaleFactor = 1,
        poisonHeadcrabDamage = 60,
        statusDurationBonus = 0,
        breakHealthLeft = 0.2,
        shockDamageIncrease = 0.15,
        frostbiteSlow = 0.4,
        eliteHealthScaleAdd = 0,
        eliteHealthScaleMultiplier = 1,
        eliteMutationProbability = 0,
        mutationProbability = 0,
        additionalPack = 0,
        additionalAmmoBoxes = 2,
        xpMultiStart = 1,
        xpMultiEnd = 1,
    },
    [2] = {
        name = "HARD",
		description = "A harder difficulty, with more damage and health added to enemies.",
        damageMultiplier = 1.1,
        enemyCountMultiplier = 1.3,
        rewardMultiplier = 0.8,
        healthMultiplier = 1.25,
        startMoneyMultiplier = 0.9,
        spawnRadiusMultiplier = 0.75,
        maxEnemiesAliveScaleFactor = 1.15,
        poisonHeadcrabDamage = 65,
        statusDurationBonus = 2,
        breakHealthLeft = 0.15,
        shockDamageIncrease = 0.20,
        frostbiteSlow = 0.5,
        eliteHealthScaleAdd = 0.1,
        eliteHealthScaleMultiplier = 1,
        eliteMutationProbability = 0.1,
        mutationProbability = 0.1,
        additionalPack = 1,
        additionalAmmoBoxes = 1,
        xpMultiStart = 1,
        xpMultiEnd = 2,
    },
    [3] = {
        name = "REALISM",
		description = "Standard difficulty. Enemies now have some new changes to their AI.",
        damageMultiplier = 1.15,
        enemyCountMultiplier = 1.5,
        rewardMultiplier = 0.6,
        healthMultiplier = 1.5,
        startMoneyMultiplier = 0.8,
        spawnRadiusMultiplier = 0.5,
        maxEnemiesAliveScaleFactor = 1.25,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 4,
        breakHealthLeft = 0.15,
        shockDamageIncrease = 0.25,
        frostbiteSlow = 0.6,
        eliteHealthScaleAdd = 0.075,
        eliteHealthScaleMultiplier = 1,
        eliteMutationProbability = 0.2,
        mutationProbability = 0.20,
        additionalPack = 0,
        additionalAmmoBoxes = 0,
        xpMultiStart = 1,
        xpMultiEnd = 2.5,
    },
    [4] = {
        name = "NIGHTMARE",
		description = "This is a harsh difficulty. More enemies get more changes, and enemies are plentiful and hit harder.",
        damageMultiplier = 1.25,
        enemyCountMultiplier = 1.5,
        rewardMultiplier = 0.5,
        healthMultiplier = 1.5,
        startMoneyMultiplier = 0.75,
        spawnRadiusMultiplier = 0.5,
        maxEnemiesAliveScaleFactor = 1.25,
        poisonHeadcrabDamage = 80,
        statusDurationBonus = 5,
        breakHealthLeft = 0.15,
        shockDamageIncrease = 0.3,
        frostbiteSlow = 0.7,
        eliteHealthScaleAdd = 0.1,
        eliteHealthScaleMultiplier = 1.1,
        eliteMutationProbability = 0.30,
        mutationProbability = 0.30,
        additionalPack = 2,
        additionalAmmoBoxes = 0,
        xpMultiStart = 1.25,
        xpMultiEnd = 3.75,
    },
    [5] = {
        name = "APOCALYPSE",
		description = "Extremely brutal. Not reccommended to play without mastering other difficulties.",
        damageMultiplier = 1.3,
        enemyCountMultiplier = 1.5,
        rewardMultiplier = 0.4,
        healthMultiplier = 1.5,
        startMoneyMultiplier = 0.6,
        spawnRadiusMultiplier = 0.4,
        maxEnemiesAliveScaleFactor = 1.3,
        poisonHeadcrabDamage = 90,
        statusDurationBonus = 6,
        breakHealthLeft = 0.15,
        shockDamageIncrease = 0.40,
        frostbiteSlow = 0.75,
        eliteHealthScaleAdd = 0.125,
        eliteHealthScaleMultiplier = 1.2,
        eliteMutationProbability = 0.45,
        mutationProbability = 0.40,
        additionalPack = 3,
        additionalAmmoBoxes = 0,
        xpMultiStart = 1.5,
        xpMultiEnd = 4,
    }
}

-- Making sure that all all keys are present
local requiredKeys = {
    "name",
    "damageMultiplier",
    "enemyCountMultiplier",
    "rewardMultiplier",
    "healthMultiplier",
    "startMoneyMultiplier",
    "spawnRadiusMultiplier",
    "maxEnemiesAliveScaleFactor",
    "poisonHeadcrabDamage",
    "statusDurationBonus",
    "breakHealthLeft",
    "shockDamageIncrease",
    "frostbiteSlow",
    "eliteHealthScaleAdd",
    "eliteHealthScaleMultiplier",
    "eliteMutationProbability",
    "mutationProbability",
    "additionalPack",
    "additionalAmmoBoxes",
}

for _, difficulty in pairs( HORDE.Difficulty ) do
    for _, key in pairs( requiredKeys ) do
        if difficulty[key] == nil then
            print( "Difficulty " .. difficulty.name .. " is missing key " .. key )
            ErrorNoHalt( "Difficulty " .. difficulty.name .. " is missing key " .. key .. "\n" )
        end
    end
end
